<section class="contact">
    <h1>Contact</h1>
    <form method="post" action="index.php?page=newMessage" enctype="multipart/form-data">
        <p>
            <label for='name'>Nom : </label>
            <input type="text" name="name" id="name">
        </p>
        <p>
            <label for='email'>Email : </label>
            <input type="email" name="email" id="email">
        </p>
        <p>
            <label for='subject'>Sujet : </label>
            <input type="text" name="subject" id="subject">
        </p>
        <p>
            <label for='text'>Message : </label>
            <textarea id="text" name="text" ></textarea>
        </p>
        <button type="submit">Envoyer</button>
    </form>


</section>