<!-- Tableau de présentation -->
<h1>Gestion des Albums</h1>
<!-- Bouton pour ajouter une entrée au tableau -->
<button type="button" id="newEntry" >Ajouter un album</button>
<table id="dashboardTable">
    <thead>
        <tr>
            <th>Titre</th>
            <th>Artiste</th>
            <th>Date de sortie</th>
            <th>Description</th>
            <th>Image</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($albumsTable as $album): ?>
            <tr>
                <td> <?= htmlspecialchars($album['title']) ?> </td>
                <td> <?= htmlspecialchars($album['name']) ?> </td>
                <td> <?= htmlspecialchars($album['publication_date']) ?> </td>
                <td> <?= htmlspecialchars($album['description']) ?> </td>
                <td> <img src="<?= htmlspecialchars($album['src'])?>" alt ="<?= htmlspecialchars($album['alt'])?>"> </td>
                <td><button class="edit" data-id="<?= $album['id'] ?>" ><i class="fas fa-pen-nib"></i></button>
                </td>
                <td><button type ="button" class ="delete" data-id="<?= $album['id'] ?>"><i class="fas fa-trash-alt"></i></button></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<!-- Formulaire pour ajouter ou modifier-->

    <form class="hide" id="form" data-edit="" method="post" enctype="multipart/form-data">
       <fieldset>
           <legend><h2><?= isset($_GET['id']) ? "Modifier la fiche album" : "Ajouter un album" ?></h2></legend>
            <div class="hide">
                <label for="id">ID</label>
                <input type="text" name ="id" value ="<?= isset($_GET['id']) ? htmlspecialchars($editAlbum['id'] ) : "" ?>">
            </div>

            <p>
                <label for="title">Titre : </label>
                <input name ="title" id="title" type="text" value ="<?= isset($_GET['id']) ?  htmlspecialchars($editAlbum['title']) : "" ?>">
            </p>
 
            <p>
            <label for="name">Artiste : </label>
                <select id="name" name="name">
                    <?php foreach($allArtists as $artist): ?>
                        <option value ="<?= htmlspecialchars($artist['id']) ?>"  <?= (isset($_GET['id']) && $artist['id'] == $editAlbum['id_artist']) ? "selected" : "" ?> > <?= htmlspecialchars( $artist['name']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </p>

            <p>
                <label for="date">Date de sortie :</label>
                <input name ="date" id="date" type="date" value ="<?= isset($_GET['id']) ?  htmlspecialchars($editAlbum['publication_date']) : "" ?>">
            </p>

            <p>
                <label for="image">Image :</label>
                <input type="file" id="image" name="image">
                    <img src="<?= isset($_GET['id']) ? htmlspecialchars($editAlbum['src']) : "" ?>" alt ="<?= isset($_GET['id']) ? htmlspecialchars($editAlbum['alt']) : "" ?>">
            </p>
                
            <p>
                <label for="alt">Description de l'image :</label>
                <input id="alt" name ="alt" type="text" value ="<?= isset($_GET['id']) ? htmlspecialchars($editAlbum['alt']) : "" ?>">
            </p>

            <p>
                <label for="text">Texte de présentation :</label>
            </p>
            <textarea id="text" name="text" rows="30" cols="70"><?= (isset($_GET['id'])) ? htmlspecialchars($editAlbum['description']) : "" ?></textarea>
        </fieldset>

    <!-- <button type="button" id="a ddEdit" >Modifier le Plat</button> -->
    
    <button type="button" id="formButton" ><?= isset($_GET['id']) ? "Modifier" : "Ajouter" ?></button>
    <button type="button" id="cancelFormButton" >Annuler</button>
    
    </form>
                    